export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const GET_QUESTION = 'GET_QUESTION';
export const LISTNER_SIGNUP = 'LISTNER_SIGNUP';
export const PROFESSIONAL_LOGIN = 'PROFESSIONAL_LOGIN';
export const PROFESSIONAL_SIGNUP = 'PROFESSIONAL_SIGNUP';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_SIGNUP = 'USER_SIGNUP';
export const GET_RECENT_JOIN = 'GET_RECENT_JOIN';
export const GET_LISTNER_DASHBOARD = 'GET_LISTNER_DASHBOARD';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_USER_DASHBOARD = 'GET_USER_DASHBOARD';
export const GET_PROFESIONAL_DASHBOARD = 'GET_PROFESIONAL_DASHBOARD';
export const GET_LISTNER_LISTING = 'GET_LISTNER_LISTING';
export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const GET_PROFESSIONAL_LISTING = 'GET_PROFESSIONAL_LISTING';
export const GET_USER_LISTING = 'GET_USER_LISTING';
export const ADMIN_CHANGE_USER_STATUS = 'ADMIN_CHANGE_USER_STATUS';
export const ADMIN_USER_DELETE = 'ADMIN_USER_DELETE';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const GET_PROFILE_BY_ID = 'GET_PROFILE_BY_ID';
export const SUBSCRIBE = 'SUBSCRIBE';



